package github

import (
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"strings"
	"time"

	gh "github.com/google/go-github/v81/github"
	"github.com/hashicorp/go-retryablehttp"
)

type Client struct {
	repo, branch, owner string
	api                 *gh.Client
}

func New(token, project, branch string) *Client {
	retry := retryablehttp.NewClient()
	retry.RetryMax = 4
	retry.RetryWaitMin = 500 * time.Millisecond
	retry.RetryWaitMax = 5 * time.Second
	retry.Logger = nil
	c := &Client{repo: project, branch: branch, api: gh.NewClient(retry.StandardClient()).WithAuthToken(token)}
	if parts := strings.SplitN(project, "/", 2); len(parts) == 2 {
		c.owner, c.repo = parts[0], parts[1]
	}
	return c
}

func (c *Client) Owner() string  { return c.owner }
func (c *Client) Repo() string   { return c.repo }
func (c *Client) Branch() string { return c.branch }
func (c *Client) WebURL() string { return fmt.Sprintf("https://github.com/%s/%s", c.owner, c.repo) }
func (c *Client) RawURL(file string) string {
	return fmt.Sprintf("https://raw.githubusercontent.com/%s/%s/%s/%s", c.owner, c.repo, c.branch, strings.TrimLeft(file, "/"))
}

func (c *Client) EnsureRepo(ctx context.Context) error {
	user, _, err := c.api.Users.Get(ctx, "")
	if err != nil {
		return fmt.Errorf("github user: %w", err)
	}
	if c.owner == "" {
		c.owner = user.GetLogin()
	}
	repo, _, err := c.api.Repositories.Get(ctx, c.owner, c.repo)
	if err == nil {
		if c.branch == "" {
			c.branch = repo.GetDefaultBranch()
		}
		if c.branch == "" {
			c.branch = "main"
		}
		return nil
	}
	if !isStatus(err, http.StatusNotFound) {
		return fmt.Errorf("github repository: %w", err)
	}
	request := &gh.Repository{Name: gh.Ptr(c.repo), Private: gh.Ptr(false), Description: gh.Ptr("Personal OpenClash rules generated by ClashRulePilot")}
	org := ""
	if !strings.EqualFold(c.owner, user.GetLogin()) {
		org = c.owner
	}
	repo, _, err = c.api.Repositories.Create(ctx, org, request)
	if err != nil {
		return fmt.Errorf("create rules repository: %w", err)
	}
	if c.branch == "" {
		c.branch = repo.GetDefaultBranch()
	}
	if c.branch == "" {
		c.branch = "main"
	}
	return nil
}

func (c *Client) GetFile(ctx context.Context, file string) ([]byte, string, error) {
	content, _, _, err := c.api.Repositories.GetContents(ctx, c.owner, c.repo, strings.TrimLeft(file, "/"), &gh.RepositoryContentGetOptions{Ref: c.branch})
	if err != nil {
		if isStatus(err, http.StatusNotFound) {
			return nil, "", nil
		}
		return nil, "", err
	}
	if content == nil {
		return nil, "", fmt.Errorf("%s is not a file", file)
	}
	data, err := content.GetContent()
	if err != nil {
		return nil, "", fmt.Errorf("decode %s: %w", file, err)
	}
	return []byte(data), content.GetSHA(), nil
}

func (c *Client) CommitFiles(ctx context.Context, files map[string][]byte, message string) (string, error) {
	if len(files) == 0 {
		return "", nil
	}
	ref, _, err := c.api.Git.GetRef(ctx, c.owner, c.repo, "heads/"+c.branch)
	baseCommitSHA, baseTreeSHA := "", ""
	if err == nil {
		baseCommitSHA = ref.GetObject().GetSHA()
		commit, _, err := c.api.Git.GetCommit(ctx, c.owner, c.repo, baseCommitSHA)
		if err != nil {
			return "", err
		}
		baseTreeSHA = commit.GetTree().GetSHA()
	} else if !isStatus(err, http.StatusNotFound) && !isStatus(err, http.StatusConflict) {
		return "", err
	}

	entries := make([]*gh.TreeEntry, 0, len(files))
	for name, data := range files {
		encoded := base64.StdEncoding.EncodeToString(data)
		blob, _, err := c.api.Git.CreateBlob(ctx, c.owner, c.repo, gh.Blob{Content: &encoded, Encoding: gh.Ptr("base64")})
		if err != nil {
			return "", fmt.Errorf("create blob %s: %w", name, err)
		}
		entries = append(entries, &gh.TreeEntry{Path: gh.Ptr(name), Mode: gh.Ptr("100644"), Type: gh.Ptr("blob"), SHA: blob.SHA})
	}
	tree, _, err := c.api.Git.CreateTree(ctx, c.owner, c.repo, baseTreeSHA, entries)
	if err != nil {
		return "", err
	}
	commit := gh.Commit{Message: gh.Ptr(message), Tree: &gh.Tree{SHA: tree.SHA}}
	if baseCommitSHA != "" {
		commit.Parents = []*gh.Commit{{SHA: gh.Ptr(baseCommitSHA)}}
	}
	created, _, err := c.api.Git.CreateCommit(ctx, c.owner, c.repo, commit, nil)
	if err != nil {
		return "", err
	}
	if baseCommitSHA == "" {
		_, _, err = c.api.Git.CreateRef(ctx, c.owner, c.repo, gh.CreateRef{Ref: "refs/heads/" + c.branch, SHA: created.GetSHA()})
	} else {
		_, _, err = c.api.Git.UpdateRef(ctx, c.owner, c.repo, "heads/"+c.branch, gh.UpdateRef{SHA: created.GetSHA(), Force: gh.Ptr(false)})
	}
	if err != nil {
		return "", fmt.Errorf("update branch (another commit may have won the race): %w", err)
	}
	return created.GetSHA(), nil
}

func isStatus(err error, status int) bool {
	if response, ok := err.(*gh.ErrorResponse); ok && response.Response != nil {
		return response.Response.StatusCode == status
	}
	return false
}
