package rules

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
	"time"
)

type Match string

const (
	Exact  Match = "exact"
	Suffix Match = "suffix"
)

type Action string

const (
	Direct Action = "direct"
	Proxy  Action = "proxy"
)

type Rule struct {
	Domain    string    `json:"domain"`
	Match     Match     `json:"match"`
	Action    Action    `json:"action"`
	CreatedBy int64     `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
}
type Store struct {
	Version int    `json:"version"`
	Rules   []Rule `json:"rules"`
}

func Empty() Store { return Store{Version: 1, Rules: []Rule{}} }
func Decode(b []byte) (Store, error) {
	if len(strings.TrimSpace(string(b))) == 0 {
		return Empty(), nil
	}
	var s Store
	if err := json.Unmarshal(b, &s); err != nil {
		return Store{}, err
	}
	if s.Version == 0 {
		s.Version = 1
	}
	return s, nil
}
func Encode(s Store) ([]byte, error) {
	sort.Slice(s.Rules, func(i, j int) bool {
		a, b := s.Rules[i], s.Rules[j]
		if a.Domain != b.Domain {
			return a.Domain < b.Domain
		}
		if a.Match != b.Match {
			return a.Match < b.Match
		}
		return a.Action < b.Action
	})
	return json.MarshalIndent(s, "", "  ")
}
func (s Store) Find(domain string, match Match) (int, *Rule) {
	for i := range s.Rules {
		if s.Rules[i].Domain == domain && s.Rules[i].Match == match {
			return i, &s.Rules[i]
		}
	}
	return -1, nil
}
func (s *Store) Add(r Rule) (conflict *Rule, duplicate bool) {
	_, old := s.Find(r.Domain, r.Match)
	if old == nil {
		s.Rules = append(s.Rules, r)
		return nil, false
	}
	if old.Action == r.Action {
		return old, true
	}
	return old, false
}
func (s *Store) Move(r Rule) {
	i, _ := s.Find(r.Domain, r.Match)
	if i >= 0 {
		s.Rules[i] = r
	} else {
		s.Rules = append(s.Rules, r)
	}
}
func (s *Store) Remove(domain string, match *Match) int {
	n := 0
	out := s.Rules[:0]
	for _, r := range s.Rules {
		if r.Domain == domain && (match == nil || r.Match == *match) {
			n++
			continue
		}
		out = append(out, r)
	}
	s.Rules = out
	return n
}

func Render(s Store, action Action, proxyGroup string) []byte {
	var rs []Rule
	for _, r := range s.Rules {
		if r.Action == action {
			rs = append(rs, r)
		}
	}
	sort.Slice(rs, func(i, j int) bool {
		if rs[i].Domain != rs[j].Domain {
			return rs[i].Domain < rs[j].Domain
		}
		return rs[i].Match < rs[j].Match
	})
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by ClashRulePilot. Action: %s\n# Do not edit; change data/personal_rules.json through the Bot.\npayload:\n", action)
	for _, r := range rs {
		token := "DOMAIN," + r.Domain
		if r.Match == Suffix {
			token = "DOMAIN-SUFFIX," + r.Domain
		}
		fmt.Fprintf(&b, "  - %s\n", token)
	}
	_ = proxyGroup
	return []byte(b.String())
}
