services:
  clashrulepilot:
    image: guanren/clashrulepilot:latest
    pull_policy: always
    container_name: clashrulepilot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    read_only: true
    tmpfs:
      - /tmp
